package com.nikijulHypixel.bazaar;

public enum AllItems {

	/* Farming ID = 100 */
	BROWN_MUSHROOM("BROWN_MUSHROOM", 100, "FARMING"),
	ENCHANTED_BROWN_MUSHROOM("ENCHNATED_BROWN_MUSHROOM", 101, "FARMING"),
	BROWN_MUSHROOM_BLOCK("HUGE_MUSHROOM_1", 102, "FARMING"),
	ENCHANTED_BROWN_MUSHROOM_BLOCK("ENCHANTED_HUGE_MUSHROOM_1", 103, "FARMING"),

	CACTUS("CACTUS", 104, "FARMING"),
	ENCHANTED_CACTUS("ENCHANTED_CACTUS", 105, "FARMING"),
	ENCHANTED_CACTUS_GREEN("ENCHANTED_CACTUS_GREEN", 106, "FARMING"),

	CARROT("CARROT_ITEM", 107, "FARMING"),
	ENCHANTED_CARROT("ENCHANTED_CARROT", 108, "FARMING"),
	ENCHANTED_CARROT_STICK("ENCHANTED_CARROT_ON_A_STICK", 109, "FARMING"),
	ENCHANTED_GOLDEN_CARROT("ENCHANTED_GOLDEN_CARROT", 110, "FARMING"),

	COCOA_BEANS("INK_SACK:3", 111, "FARMING"),
	ENCHANTED_COCOA("ENCHANTED_COCOA", 112, "FARMING"),
	ENCHANTED_COOKIE("ENCHANTED_COOKIE", 113, "FARMING"),

	MELON("MELON", 114, "FARMING"),
	ENCHANTED_MELON("ENCHANTED_MELON", 115, "FARMING"),
	ENCHANTED_GLISTERING_MELON("ENCHANTED_GLISTERING_MELON", 116, "FARMING"),
	ENCHANTED_MELON_BLOCK("ENCHANTED_MELON_BLOCK", 117, "FARMING"),

	NETHER_WART("NETHER_STALK", 118, "FARMING"),
	ENCHANTED_NETHER_WART("ENCHANTED_NETHER_STALK", 119, "FARMING"),

	POTATO("POTATO_ITEM", 120, "FARMING"),
	ENCHANTED_POTATO("ENCHANTED_POTATO", 121, "FARMING"),
	ENCHANTED_BAKED_POTATO("ENCHANTED_BAKED_POTATO", 122, "FARMING"),
	HOT_POTATO_BOOK("HOT_POTATO_BOOK", 123, "FARMING"),

	PUMPKIN("PUMPKIN", 124, "FARMING"),
	ENCHANTED_PUMPKIN("ENCHANTED_PUMPKIN", 125, "FARMING"),

	RED_MUSHROOM("RED_MUSHROOM", 126, "FARMING"),
	ENCHANTED_RED_MUSHROOM("ENCHNATED_RED_MUSHROOM", 127, "FARMING"),
	RED_MUSHROOM_BLOCK("HUGE_MUSHROOM_2", 128, "FARMING"),
	ENCHANTED_RED_MUSHROOM_BLOCK("ENCHANTED_HUGE_MUSHROOM_2", 129, "FARMING"),

	SEEDS("SEEDS", 130, "FARMING"),
	ENCHANTED_SEEDS("ENCHANTED_SEEDS", 131, "FARMING"),

	SUGAR_CANE("SUGAR_CANE", 132, "FARMING"),
	ENCHANTED_SUGAR("ENCHANTED_SUGAR", 133, "FARMING"),
	ENCHANTED_SUGAR_CANE("ENCHANTED_SUGAR_CANE", 134, "FARMING"),
	ENCHANTED_PAPER("ENCHANTED_PAPER", 135, "FARMING"),

	WHEAT("WHEAT", 136, "FARMING"),
	ENCHANTED_BREAD("ENCHANTED_BREAD", 137, "FARMING"),
	HAY_BALE("HAY_BLOCK", 138, "FARMING"),
	ENCHANTED_HAY_BALE("ENCHANTED_HAY_BLOCK", 139, "FARMING"),

	/* Animals ID = 200 */
	BEEF("RAW_BEEF", 200, "ANIMALS"),
	ENCHANTED_BEEF("ENCHANTED_RAW_BEEF", 201, "ANIMALS"),

	CHICKEN("RAW_CHICKEN", 202, "ANIMALS"),
	ENCHANTED_CHICKEN("ENCHANTED_RAW_CHICKEN", 203, "ANIMALS"),

	ENCHANTED_EGG("ENCHANTED_EGG", 204, "ANIMALS"),
	SUPER_EGG("SUPER_EGG", 205, "ANIMALS"),
	ENCHANTED_CAKE("ENCHANTED_CAKE", 206, "ANIMALS"),

	FEATHER("FEATHER", 207, "ANIMALS"),
	ENCHANTED_FEATHER("ENCHANTED_FEATHER", 208, "ANIMALS"),

	LEATHER("LEATHER", 208, "ANIMALS"),
	ENCHANTED_LEATHER("ENCHANTED_LEATHER", 209, "ANIMALS"),

	MUTTON("MUTTON", 210, "ANIMALS"),
	ENCHANTED_MUTTON("ENCHANTED_MUTTON", 211, "ANIMALS"),
	ENCHANTED_COOKED_MUTTON("ENCHANTED_COOKED_MUTTON", 212, "ANIMALS"),

	PORK("PORK", 213, "ANIMALS"),
	ENCHANTED_PORK("ENCHANTED_PORK", 214, "ANIMALS"),
	ENCHANTED_COOKED_PORK("ENCHANTED_GRILLED_PORK", 215, "ANIMALS"),

	RABBIT("RABBIT", 216, "ANIMALS"),
	ENCHANTED_RABBIT("ENCHANTED_RABBIT", 217, "ANIMALS"),

	RABBIT_FOOT("RABBIT_FOOT", 218, "ANIMALS"),
	ENCHANTED_RABBIT_FOOT("ENCHANTED_RABBIT_FOOT", 219, "ANIMALS"),

	RABBIT_HIDE("RABBIT_HIDE", 220, "ANIMALS"),
	ENCHANTED_RABBIT_HIDE("ENCHANTED_RABBIT_HIDE", 221, "ANIMALS"),

	/* Mining ID = 300 */
	COAL("COAL", 300, "MINING"),
	ENCHANTED_COAL("ENCHANTED_COAL", 301, "MINING"),
	ENCHANTED_CHARCOAL("ENCHANTED_CHARCOAL", 302, "MINING"),
	ENCHANTED_COAL_BLOCK("ENCHANTED_COAL_BLOCK", 303, "MINING"),

	COBBLESTONE("COBBLESTONE", 304, "MINING"),
	ENCHANTED_COBBLESTONE("ENCHANTED_COBBLESTONE", 305, "MINING"),

	DIAMOND("DIAMOND", 306, "MINING"),
	ENCHANTED_DIAMOND("ENCHANTED_DIAMOND", 307, "MINING"),
	ENCHANTED_DIAMOND_BLOCK("ENCHANTED_DIAMOND_BLOCK", 308, "MINING"),

	EMERALD("EMERALD", 309, "MINING"),
	ENCHANTED_EMERALD("ENCHANTED_EMERALD", 310, "MINING"),
	ENCHANTED_EMERALD_BLOCK("ENCHANTED_EMERALD_BLOCK", 311, "MINING"),

	END_STONE("ENDER_STONE", 312, "MINING"),
	ENCHANTED_ENDSTONE("ENCHANTED_ENDSTONE", 313, "MINING"),

	FLINT("FLINT", 314, "MINING"),
	ENCHANTED_FLINT("ENCHANTED_FLINT", 315, "MINING"),

	GLOWSTONE_DUST("GLOWSTONE_DUST", 316, "MINING"),
	ENCHANTED_GLOWSTONE_DUST("ENCHANTED_GLOWSTONE_DUST", 317, "MINING"),
	ENCHANTED_GLOWSTONE("ENCHANTED_GLOWSTONE", 318, "MINING"),

	GOLD_INGOT("GOLD_INGOT", 319, "MINING"),
	ENCHANTED_GOLD("ENCHANTED_GOLD", 320, "MINING"),
	ENCHANTED_GOLD_BLOCK("ENCHANTED_GOLD_BLOCK", 321, "MINING"),

	GRAVEL("GRAVEL", 323, "MINING"),

	ICE("ICE", 324, "MINING"),
	ENCHANTED_ICE("ENCHANTED_ICE", 325, "MINING"),
	PACKED_ICE("PACKED_ICE", 326, "MINING"),
	ENCHANTED_PACKED_ICE("ENCHANTED_PACKED_ICE", 327, "MINING"),

	IRON_INGOT("IRON_INGOT", 328, "MINING"),
	ENCHANTED_IRON("ENCHANTED_IRON", 329, "MINING"),
	ENCHANTED_IRON_BLOCK("ENCHANTED_IRON_BLOCK", 330, "MINING"),

	LAPIS_LAZULI("INK_SACK:3", 331, "MINING"),
	ENCHANTED_LAPIS_LAZULI("ENCHANTED_LAPIS_LAZULI", 332, "MINING"),
	ENCHANTED_LAPIS_LAZULI_BLOCK("ENCHANTED_LAPIS_LAZULI_BLOCK", 333, "MINING"),

	NETHERRACK("NETHERRACK", 334, "MINING"),

	OBSIDIAN("OBSIDIAN", 335, "MINING"),
	ENCHANTED_OBSIDIAN("ENCHANTED_OBSIDIAN", 336, "MINING"),

	QUARTZ("QUARTZ", 337, "MINING"),
	ENCHANTED_QUARTZ("ENCHANTED_QUARTZ", 338, "MINING"),
	ENCHANTED_QUARTZ_BLOCK("ENCHANTED_QUARTZ_BLOCK", 339, "MINING"),

	REDSTONE("REDSTONE", 340, "MINING"),
	ENCHANTED_REDSTONE("ENCHANTED_REDSTONE", 341, "MINING"),
	ENCHANTED_REDSTONE_BLOCK("ENCHANTED_REDSTONE_BLOCK", 342, "MINING"),

	SAND("SAND", 343, "MINING"),

	SNOW_BALL("SNOW_BALL", 344, "MINING"),
	SNOW_BLOCK("SNOW_BLOCK", 345, "MINING"),
	ENCHANTED_SNOW_BLOCK("ENCHANTED_SNOW_BLOCK", 346, "MINING"),

	/* Combat ID = 400 */
	BLAZE_ROD("BLAZE_ROD", 400, "COMBAT"),
	ENCHANTED_BLAZE_POWDER("ENCHANTED_BLAZE_POWDER", 401, "COMBAT"),
	ENCHANTED_BLAZE_ROD("ENCHANTED_BLAZE_ROD", 402, "COMBAT"),

	BONE("BONE", 403, "COMBAT"),
	ENCHANTED_BONE("ENCHANTED_BONE", 404, "COMBAT"),

	ENDER_PEARL("ENDER_PEARL", 405, "COMBAT"),
	ENCHANTED_ENDER_PEARL("ENCHANTED_ENDER_PEARL", 406, "COMBAT"),
	ENCHANTED_EYE_OF_ENDER("ENCHANTED_EYE_OF_ENDER", 407, "COMBAT"),

	GHAST_TEAR("GHAST_TEAR", 408, "COMBAT"),
	ENCHANTED_GHAST_TEAR("ENCHANTED_GHAST_TEAR", 409, "COMBAT"),

	GUNPOWDER("SULPHUR", 410, "COMBAT"),
	ENCHANTED_GUNPOWDER("ENCHANTED_GUNPOWDER", 411, "COMBAT"),
	ENCHANTED_FIREWORK_ROCKET("ENCHANTED_FIREWORK_ROCKET", 412, "COMBAT"),

	MAGMA_CREAM("MAGMA_CREAM", 413, "COMBAT"),
	ENCHANTED_MAGMA_CREAM("ENCHANTED_MAGMA_CREAM", 414, "COMBAT"),

	ROTTEN_FLESH("ROTTEN_FLESH", 415, "COMBAT"),
	ENCHANTED_ROTTEN_FLESH("ENCHANTED_ROTTEN_FLESH", 416, "COMBAT"),

	SLIME_BALL("SLIME_BALL", 417, "COMBAT"),
	ENCHANTED_SLIME_BALL("ENCHANTED_SLIME_BALL", 418, "COMBAT"),
	ENCHANTED_SLIME_BLOCK("ENCHANTED_SLIME_BLOCK", 419, "COMBAT"),

	SPIDER_EYE("SPIDER_EYE", 420, "COMBAT"),
	ENCHANTED_SPIDER_EYE("ENCHANTED_SPIDER_EYE", 421, "COMBAT"),
	ENCHANTED_FERMENTED_SPIDER_EYE("ENCHANTED_FERMENTED_SPIDER_EYE", 422, "COMBAT"),

	STRING("STRING", 423, "COMBAT"),
	ENCHANTED_STRING("ENCHANTED_STRING", 424, "COMBAT"),

	/* Wood ID = 500 */
	ACACIA_LOG("LOG_2", 500, "WOOD"),
	ENCHANTED_ACACIA_LOG("ENCHANTED_ACACIA_LOG", 501, "WOOD"),

	BIRCH_LOG("LOG:2", 502, "WOOD"),
	ENCHANTED_BIRCH_LOG("ENCHANTED_BIRCH_LOG", 503, "WOOD"),

	DARK_OAK_LOG("LOG_2:1", 504, "WOOD"),
	ENCHANTED_DARK_OAK_LOG("ENCHANTED_DARK_OAK_LOG", 505, "WOOD"),

	JUNGLE_LOG("LOG:3", 506, "WOOD"),
	ENCHANTED_JUNGLE_LOG("ENCHANTED_JUNGLE_LOG", 507, "WOOD"),

	OAK_LOG("LOG", 508, "WOOD"),
	ENCHANTED_OAK_LOG("ENCHANTED_OAK_LOG", 509, "WOOD"),

	SPRUCE_LOG("LOG:1", 510, "WOOD"),
	ENCHANTED_SPRUCE_LOG("ENCHANTED_SPRUCE_LOG", 511, "WOOD"),

	/* Fishing ID = 600 */
	CLAY_BALL("CLAY_BALL", 600, "FISHING"),
	ENCHANTED_CLAY_BALL("ENCHANTED_CLAY_BALL", 601, "FISHING"),

	FISH("RAW_FISH", 602, "FISHING"),
	ENCHANTED_FISH("ENCHANTED_RAW_FISH", 603, "FISHING"),
	ENCHANTED_COOKED_FISH("ENCHANTED_COOKED_FISH", 604, "FISHING"),

	INK_SACK("INK_SACK", 605, "FISHING"),
	ENCHANTED_INK_SACK("ENCHANTED_INK_SACK", 606, "FISHING"),

	PRISMARINE_CRYSTALS("PRISMARINE_CRYSTALS", 607, "FISHING"),
	ENCHANTED_PRISMARINE_CRYSTALS("ENCHANTED_PRISMARINE_CRYSTALS", 608, "FISHING"),

	PRISMARINE_SHARD("PRISMARINE_SHARD", 609, "FISHING"),
	ENCHANTED_PRISMARINE_SHARD("ENCHANTED_PRISMARINE_SHARD", 610, "FISHING"),

	PUFFERFISH("RAW_FISH:3", 611, "FISHING"),
	ENCHANTED_PUFFERFISH("ENCHANTED_PUFFERFISH", 612, "FISHING"),

	SALMON("RAW_FISH:1", 613, "FISHING"),
	ENCHANTED_SALMON("ENCHANTED_RAW_SALMON", 614, "FISHING"),
	ENCHANTED_COOKED_SALMON("ENCHANTED_COOKED_SALMON", 615, "FISHING"),

	SPONGE("SPONGE", 616, "FISHING"),
	ENCHANTED_SPONGE("ENCHANTED_SPONGE", 617, "FISHING"),

	WATER_LILY("WATER_LILY", 618, "FISHING"),
	ENCHANTED_WATER_LILY("ENCHANTED_WATER_LILY", 619, "FISHING"),

	/* Hypixel-Items ID = 700 */
	COMPACTOR("COMPACTOR", 700, "HYPIXEL"),
	SUPER_COMPACTOR_3000("SUPER_COMPACTOR_3000", 701, "HYPIXEL"),

	GREEN_CANDY("GREEN_CANDY", 702, "HYPIXEL"),
	PURPLE_CANDY("PURPLE_CANDY", 703, "HYPIXEL"),

	REVENANT_FLESH("REVENANT_FLESH", 704, "HYPIXEL"),
	REVENANT_VISCERA("REVENANT_VISCERA", 705, "HYPIXEL"),

	STOCK_OF_STONKS("STOCK_OF_STONKS", 706, "HYPIXEL"),

	SUMMONING_EYE("SUMMONING_EYE", 707, "HYPIXEL"),

	TARANTULA_WEB("TARANTULA_WEB", 708, "HYPIXEL"),
	TARANTULA_SILK("TARANTULA_SILK", 709, "HYPIXEL"),

	WHITE_GIFT("WHITE_GIFT", 710, "HYPIXEL"),
	GREEN_GIFT("GREEN_GIFT", 711, "HYPIXEL"),
	RED_GIFT("RED_GIFT", 712, "HYPIXEL"),

	WOLF_TOOTH("WOLF_TOOTH", 713, "HYPIXEL"),
	GOLDEN_TOOTH("GOLDEN_TOOTH", 714, "HYPIXEL"),

	ENCHANTED_REDSTONE_LAMP("ENCHANTED_REDSTONE_LAMP", 715, "HYPIXEL"),

	ENCHANTED_LAVA_BUCKET("ENCHANTED_LAVA_BUCKET", 716, "HYPIXEL"),
	HAMSTER_WHEEL("HAMSTER_WHEEL", 717, "HYPIXEL"),
	FOUL_FLESH("FOUL_FLESH", 718, "HYPIXEL"),
	CATALYST("CATALYST", 719, "HYPIXEL"),

	YOUNG_FRAGMENT("YOUNG_FRAGMENT", 720, "HYPIXEL"),
	OLD_FRAGMENT("OLD_FRAGMENT", 721, "HYPIXEL"),
	WISE_FRAGMENT("WISE_FRAGMENT", 722, "HYPIEXEL"),
	PROTECTOR_FRAGMENT("PROTECTOR_FRAGMENT", 723, "HYPIXEL"),
	STRONG_FRAGMENT("STRONG_FRAGMENT", 724, "HYPIXEL"),
	UNSTABLE_FRAGMENT("UNSTABLE_FRAGMENT", 725, "HYPIXEL"),
	SUPERIOR_FRAGMENT("SUPERIOR_FRAGMENT", 726, "HYPIXEL"),

	// END
	END("END", 800, "END");

	private String ID;
	private int buttonID;
	private String category;

	private AllItems(String apiID, int buttonID, String category) {

		this.ID = apiID;
		this.buttonID = buttonID;
		this.category = category;

	}

	public String getID() {
		return ID;
	}

	public int getButtonID() {
		return buttonID;
	}

	public String getCategory() {
		return category;
	}

}
