package com.nikijulHypixel.bazaar;

public enum AllItems {

	/* Farming 35*/
	BROWN_MUSHROOM("BROWN_MUSHROOM", 0, "FARMING"),
	ENCHANTED_BROWN_MUSHROOM("ENCHNATED_BROWN_MUSHROOM", 179, "FARMING"),
	BROWN_MUSHROOM_BLOCK("HUGE_MUSHROOM_1", 1, "FARMING"),
	ENCHANTED_BROWN_MUSHROOM_BLOCK("ENCHANTED_HUGE_MUSHROOM_1", 2, "FARMING"),
	
	CACTUS("CACTUS", 3, "FARMING"),
	ENCHANTED_CACTUS("ENCHANTED_CACTUS", 4, "FARMING"),
	ENCHANTED_CACTUS_GREEN("ENCHANTED_CACTUS_GREEN", 5, "FARMING"),
	
	CARROT("CARROT_ITEM", 6, "FARMING"),
	ENCHANTED_CARROT("ENCHANTED_CARROT", 7, "FARMING"),
	ENCHANTED_CARROT_STICK("ENCHANTED_CARROT_ON_A_STICK", 8, "FARMING"),
	ENCHANTED_GOLDEN_CARROT("ENCHANTED_GOLDEN_CARROT", 9, "FARMING"),
	
	COCOA_BEANS("INK_SACK:3", 10, "FARMING"),
	ENCHANTED_COCOA("ENCHANTED_COCOA", 11, "FARMING"),
	ENCHANTED_COOKIE("ENCHANTED_COOKIE", 12, "FARMING"),
	
	MELON("MELON", 13, "FARMING"),
	ENCHANTED_MELON("ENCHANTED_MELON", 14, "FARMING"),	
	ENCHANTED_GLISTERING_MELON("ENCHANTED_GLISTERING_MELON", 15, "FARMING"),
	ENCHANTED_MELON_BLOCK("ENCHANTED_MELON_BLOCK", 16, "FARMING"),
	
	NETHER_WART("NETHER_STALK", 17, "FARMING"),
	ENCHANTED_NETHER_WART("ENCHANTED_NETHER_STALK", 18, "FARMING"),
	
	POTATO("POTATO_ITEM", 19, "FARMING"),
	ENCHANTED_POTATO("ENCHANTED_POTATO", 20, "FARMING"),
	ENCHANTED_BAKED_POTATO("ENCHANTED_BAKED_POTATO", 21, "FARMING"),
	HOT_POTATO_BOOK("HOT_POTATO_BOOK", 22, "FARMING"),
	
	PUMPKIN("PUMPKIN", 23, "FARMING"),
	ENCHANTED_PUMPKIN("ENCHANTED_PUMPKIN", 24, "FARMING"),
	
	RED_MUSHROOM("RED_MUSHROOM", 25, "FARMING"),
	ENCHANTED_RED_MUSHROOM("ENCHNATED_RED_MUSHROOM", 179, "FARMING"),
	RED_MUSHROOM_BLOCK("HUGE_MUSHROOM_2", 26, "FARMING"),
	ENCHANTED_RED_MUSHROOM_BLOCK("ENCHANTED_HUGE_MUSHROOM_2", 27, "FARMING"),
	
	SEEDS("SEEDS", 28, "FARMING"),
	ENCHANTED_SEEDS("ENCHANTED_SEEDS", 178, "FARMING"),
	
	SUGAR_CANE("SUGAR_CANE", 29, "FARMING"),
	ENCHANTED_SUGAR("ENCHANTED_SUGAR", 30, "FARMING"),
	ENCHANTED_SUGAR_CANE("ENCHANTED_SUGAR_CANE", 31, "FARMING"),
	ENCHANTED_PAPER("ENCHANTED_PAPER", 32, "FARMING"),

	WHEAT("WHEAT", 33, "FARMING"),
	ENCHANTED_BREAD("ENCHANTED_BREAD", 34, "FARMING"),
	HAY_BALE("HAY_BLOCK", 176, "FARMING"),
	ENCHANTED_HAY_BALE("ENCHANTED_HAY_BLOCK", 177, "FARMING"),
	
	/* Animals 23*/
	BEEF("RAW_BEEF", 35, "ANIMALS"),
	ENCHANTED_BEEF("ENCHANTED_RAW_BEEF", 36, "ANIMALS"),
	
	CHICKEN("RAW_CHICKEN", 37, "ANIMALS"),
	ENCHANTED_CHICKEN("ENCHANTED_RAW_CHICKEN", 38, "ANIMALS"),
	
	ENCHANTED_EGG("ENCHANTED_EGG", 39, "ANIMALS"),
	SUPER_EGG("SUPER_EGG", 40, "ANIMALS"),
	ENCHANTED_CAKE("ENCHANTED_CAKE", 41, "ANIMALS"),
	
	FEATHER("FEATHER", 42, "ANIMALS"),
	ENCHANTED_FEATHER("ENCHANTED_FEATHER", 43, "ANIMALS"),
	
	LEATHER("LEATHER", 44, "ANIMALS"),
	ENCHANTED_LEATHER("ENCHANTED_LEATHER", 45, "ANIMALS"),
	
	MUTTON("MUTTON", 46, "ANIMALS"),
	ENCHANTED_MUTTON("ENCHANTED_MUTTON", 47, "ANIMALS"),
	ENCHANTED_COOKED_MUTTON("ENCHANTED_COOKED_MUTTON", 48, "ANIMALS"),
	
	PORK("PORK", 49, "ANIMALS"),
	ENCHANTED_PORK("ENCHANTED_PORK", 50, "ANIMALS"),
	ENCHANTED_COOKED_PORK("ENCHANTED_GRILLED_PORK", 51, "ANIMALS"),
	
	RABBIT("RABBIT", 52, "ANIMALS"),
	ENCHANTED_RABBIT("ENCHANTED_RABBIT", 53, "ANIMALS"),
	
	RABBIT_FOOT("RABBIT_FOOT", 54, "ANIMALS"),
	ENCHANTED_RABBIT_FOOT("ENCHANTED_RABBIT_FOOT", 55, "ANIMALS"),
	
	RABBIT_HIDE("RABBIT_HIDE", 56, "ANIMALS"),
	ENCHANTED_RABBIT_HIDE("ENCHANTED_RABBIT_HIDE", 57, "ANIMALS"),
	
	/* Mining 46*/
	COAL("COAL", 58, "MINING"),
	ENCHANTED_COAL("ENCHANTED_COAL", 59, "MINING"),
	ENCHANTED_CHARCOAL("ENCHANTED_CHARCOAL", 60, "MINING"),
	ENCHANTED_COAL_BLOCK("ENCHANTED_COAL_BLOCK", 61, "MINING"),
	
	COBBLESTONE("COBBLESTONE", 62, "MINING"),
	ENCHANTED_COBBLESTONE("ENCHANTED_COBBLESTONE", 63, "MINING"),
	
	DIAMOND("DIAMOND", 64, "MINING"),
	ENCHANTED_DIAMOND("ENCHANTED_DIAMOND", 65, "MINING"),
	ENCHANTED_DIAMOND_BLOCK("ENCHANTED_DIAMOND_BLOCK", 66, "MINING"),
	
	EMERALD("EMERALD", 67, "MINING"),
	ENCHANTED_EMERALD("ENCHANTED_EMERALD", 68, "MINING"),
	ENCHANTED_EMERALD_BLOCK("ENCHANTED_EMERALD_BLOCK", 69, "MINING"),
	
	END_STONE("ENDER_STONE", 70, "MINING"),
	ENCHANTED_ENDSTONE("ENCHANTED_ENDSTONE", 71, "MINING"),
	
	FLINT("FLINT", 72, "MINING"),
	ENCHANTED_FLINT("ENCHANTED_FLINT", 73, "MINING"),
	
	GLOWSTONE_DUST("GLOWSTONE_DUST", 74, "MINING"),
	ENCHANTED_GLOWSTONE_DUST("ENCHANTED_GLOWSTONE_DUST", 75, "MINING"),
	ENCHANTED_GLOWSTONE("ENCHANTED_GLOWSTONE", 76, "MINING"),
	
	GOLD_INGOT("GOLD_INGOT", 77, "MINING"),
	ENCHANTED_GOLD("ENCHANTED_GOLD", 78, "MINING"),
	ENCHANTED_GOLD_BLOCK("ENCHANTED_GOLD_BLOCK", 79, "MINING"),
	
	GRAVEL("GRAVEL", 80, "MINING"),
	
	ICE("ICE", 81, "MINING"),
	ENCHANTED_ICE("ENCHANTED_ICE", 82, "MINING"),
	PACKED_ICE("PACKED_ICE", 83, "MINING"),
	ENCHANTED_PACKED_ICE("ENCHANTED_PACKED_ICE", 84, "MINING"),
	
	IRON_INGOT("IRON_INGOT", 85, "MINING"),
	ENCHANTED_IRON("ENCHANTED_IRON", 86, "MINING"),
	ENCHANTED_IRON_BLOCK("ENCHANTED_IRON_BLOCK", 87, "MINING"),
	
	LAPIS_LAZULI("INK_SACK:3", 88, "MINING"),
	ENCHANTED_LAPIS_LAZULI("ENCHANTED_LAPIS_LAZULI", 89, "MINING"),
	ENCHANTED_LAPIS_LAZULI_BLOCK("ENCHANTED_LAPIS_LAZULI_BLOCK", 90, "MINING"),
	
	NETHERRACK("NETHERRACK", 91, "MINING"),
	
	OBSIDIAN("OBSIDIAN", 92, "MINING"),
	ENCHANTED_OBSIDIAN("ENCHANTED_OBSIDIAN", 93, "MINING"),
	
	QUARTZ("QUARTZ", 94, "MINING"),
	ENCHANTED_QUARTZ("ENCHANTED_QUARTZ", 95, "MINING"),
	ENCHANTED_QUARTZ_BLOCK("ENCHANTED_QUARTZ_BLOCK", 96, "MINING"),
	
	REDSTONE("REDSTONE", 97, "MINING"),
	ENCHANTED_REDSTONE("ENCHANTED_REDSTONE", 98, "MINING"),
	ENCHANTED_REDSTONE_BLOCK("ENCHANTED_REDSTONE_BLOCK", 99, "MINING"),
	
	SAND("SAND", 100, "MINING"),
	
	SNOW_BALL("SNOW_BALL", 101, "MINING"),
	SNOW_BLOCK("SNOW_BLOCK", 102, "MINING"),
	ENCHANTED_SNOW_BLOCK("ENCHANTED_SNOW_BLOCK", 103, "MINING"),
	
	/* Combat 24*/
	BLAZE_ROD("BLAZE_ROD", 104, "COMBAT"),
	ENCHANTED_BLAZE_POWDER("ENCHANTED_BLAZE_POWDER", 105, "COMBAT"),
	ENCHANTED_BLAZE_ROD("ENCHANTED_BLAZE_ROD", 106, "COMBAT"),
	
	BONE("BONE", 107, "COMBAT"),
	ENCHANTED_BONE("ENCHANTED_BONE", 108, "COMBAT"),
	
	ENDER_PEARL("ENDER_PEARL", 109, "COMBAT"),
	ENCHANTED_ENDER_PEARL("ENCHANTED_ENDER_PEARL", 110, "COMBAT"),
	ENCHANTED_EYE_OF_ENDER("ENCHANTED_EYE_OF_ENDER", 111, "COMBAT"),
	
	GHAST_TEAR("GHAST_TEAR", 112, "COMBAT"),
	ENCHANTED_GHAST_TEAR("ENCHANTED_GHAST_TEAR", 113, "COMBAT"),
	
	GUNPOWDER("SULPHUR", 114, "COMBAT"),
	ENCHANTED_GUNPOWDER("ENCHANTED_GUNPOWDER", 115, "COMBAT"),
	ENCHANTED_FIREWORK_ROCKET("ENCHANTED_FIREWORK_ROCKET", 181, "COMBAT"),
	
	MAGMA_CREAM("MAGMA_CREAM", 116, "COMBAT"),
	ENCHANTED_MAGMA_CREAM("ENCHANTED_MAGMA_CREAM", 117, "COMBAT"),
	
	ROTTEN_FLESH("ROTTEN_FLESH", 118, "COMBAT"),
	ENCHANTED_ROTTEN_FLESH("ENCHANTED_ROTTEN_FLESH", 119, "COMBAT"),
	
	SLIME_BALL("SLIME_BALL", 120, "COMBAT"),
	ENCHANTED_SLIME_BALL("ENCHANTED_SLIME_BALL", 121, "COMBAT"),
	ENCHANTED_SLIME_BLOCK("ENCHANTED_SLIME_BLOCK", 122, "COMBAT"),
	
	SPIDER_EYE("SPIDER_EYE", 123, "COMBAT"),
	ENCHANTED_SPIDER_EYE("ENCHANTED_SPIDER_EYE", 124, "COMBAT"),
	ENCHANTED_FERMENTED_SPIDER_EYE("ENCHANTED_FERMENTED_SPIDER_EYE", 125, "COMBAT"),
	
	STRING("STRING", 126, "COMBAT"),
	ENCHANTED_STRING("ENCHANTED_STRING", 127, "COMBAT"),
	

	/* Wood 12*/
	ACACIA_LOG("LOG_2", 128, "WOOD"),
	ENCHANTED_ACACIA_LOG("ENCHANTED_ACACIA_LOG", 129, "WOOD"),
	
	BIRCH_LOG("LOG:2", 130, "WOOD"),
	ENCHANTED_BIRCH_LOG("ENCHANTED_BIRCH_LOG", 131, "WOOD"),
	
	DARK_OAK_LOG("LOG_2:1", 132, "WOOD"),
	ENCHANTED_DARK_OAK_LOG("ENCHANTED_DARK_OAK_LOG", 133, "WOOD"),
	
	JUNGLE_LOG("LOG:3", 134, "WOOD"),
	ENCHANTED_JUNGLE_LOG("ENCHANTED_JUNGLE_LOG", 135, "WOOD"),

	OAK_LOG("LOG", 136, "WOOD"),
	ENCHANTED_OAK_LOG("ENCHANTED_OAK_LOG", 137, "WOOD"),
	
	SPRUCE_LOG("LOG:1", 138, "WOOD"),
	ENCHANTED_SPRUCE_LOG("ENCHANTED_SPRUCE_LOG", 139, "WOOD"),

	/* Fishing  20*/
	CLAY_BALL("CLAY_BALL", 140, "FISHING"),
	ENCHANTED_CLAY_BALL("ENCHANTED_CLAY_BALL", 141, "FISHING"),
	
	FISH("RAW_FISH", 142, "FISHING"),
	ENCHANTED_FISH("ENCHANTED_RAW_FISH", 143, "FISHING"),
	ENCHANTED_COOKED_FISH("ENCHANTED_COOKED_FISH", 144, "FISHING"),
	
	INK_SACK("INK_SACK", 145, "FISHING"),
	ENCHANTED_INK_SACK("ENCHANTED_INK_SACK", 146, "FISHING"),
	
	PRISMARINE_CRYSTALS("PRISMARINE_CRYSTALS", 147, "FISHING"),
	ENCHANTED_PRISMARINE_CRYSTALS("ENCHANTED_PRISMARINE_CRYSTALS", 148, "FISHING"),
	
	PRISMARINE_SHARD("PRISMARINE_SHARD", 149, "FISHING"),
	ENCHANTED_PRISMARINE_SHARD("ENCHANTED_PRISMARINE_SHARD", 150, "FISHING"),
	
	PUFFERFISH("RAW_FISH:3", 151, "FISHING"),
	ENCHANTED_PUFFERFISH("ENCHANTED_PUFFERFISH", 152, "FISHING"),
	
	SALMON("RAW_FISH:1", 153, "FISHING"),
	ENCHANTED_SALMON("ENCHANTED_RAW_SALMON", 154, "FISHING"),
	ENCHANTED_COOKED_SALMON("ENCHANTED_COOKED_SALMON", 155, "FISHING"),
	
	SPONGE("SPONGE", 156, "FISHING"),
	ENCHANTED_SPONGE("ENCHANTED_SPONGE", 157, "FISHING"),
	
	WATER_LILY("WATER_LILY", 158, "FISHING"),
	ENCHANTED_WATER_LILY("ENCHANTED_WATER_LILY", 159, "FISHING"),

	
	/* Hypixel-Items  15*/ 
	COMPACTOR("COMPACTOR", 160, "HYPIXEL"),
	SUPER_COMPACTOR_3000("SUPER_COMPACTOR_3000", 161, "HYPIXEL"),
	
	GREEN_CANDY("GREEN_CANDY", 162, "HYPIXEL"),
	PURPLE_CANDY("PURPLE_CANDY", 163, "HYPIXEL"),
	
	REVENANT_FLESH("REVENANT_FLESH", 164, "HYPIXEL"),
	REVENANT_VISCERA("REVENANT_VISCERA", 165, "HYPIXEL"),
	
	STOCK_OF_STONKS("STOCK_OF_STONKS", 166, "HYPIXEL"),
	
	SUMMONING_EYE("SUMMONING_EYE", 167, "HYPIXEL"),
	
	TARANTULA_SILK("TARANTULA_SILK", 168, "HYPIXEL"),
	TARANTULA_WEB("TARANTULA_WEB", 169, "HYPIXEL"),
	
	WHITE_GIFT("WHITE_GIFT", 170, "HYPIXEL"),
	GREEN_GIFT("GREEN_GIFT", 171, "HYPIXEL"),
	RED_GIFT("RED_GIFT", 172, "HYPIXEL"),
	
	WOLF_TOOTH("WOLF_TOOTH", 173, "HYPIXEL"),
	GOLDEN_TOOTH("GOLDEN_TOOTH", 174, "HYPIXEL"),
	ENCHANTED_REDSTONE_LAMP("ENCHANTED_REDSTONE_LAMP", 175, "HYPIXEL"),
	
	// END
	END("END", 175, "END");

	private String ID;
	private int buttonID;
	private String category;

	private AllItems(String apiID, int buttonID, String category) {

		this.ID = apiID;
		this.buttonID = buttonID;
		this.category = category;

	}

	public String getID() {
		return ID;
	}
	
	public int getButtonID() {
		return buttonID;
	}

	public String getCategory() {
		return category;
	}

}
